default:
  - 'static'

server:
  - 'static'
  - 'exec:launch'
  - 'watch'

static:
  - 'clean:scripts'
  - 'clean:styles'
  - 'clean:images'
  - 'scripts'
  - 'styles'
  - 'images'
  - 'markup'

scripts:
  - 'jshint'<% if (hasHTML5Feat) { %>
  - 'uglify:aids'<% } if (includeBrowserify) { %>
  - 'browserify'
  - 'uglify:boot'<% } else { %>
  - 'requirejs'<% } %>
  - 'clean:tmp'

styles:
  - 'sass'
  - 'autoprefixer'
  - 'cssmin'

images:
  - 'concurrent:images'

markup:<% if (includeJade) { %>
  - 'jade:index'<% } %>
  - 'newer:copy:static'
  - 'processhtml'
  - 'htmlcompressor'
