default:
  - 'static'

server:
  - 'static'
  - 'exec:launch'
  - 'watch'

static:
  - 'clean:scripts'
  - 'clean:styles'
  - 'clean:images'
  - 'scripts'
  - 'styles'
  - 'images'
  - 'markup'

scripts:
  - 'jshint'<% if (hasHTML5Feat) { %>
  - 'uglify:aids'<% } %>
  - 'browserify'
  - 'uglify:boot'
  - 'clean:tmp'

styles:
  - 'sass'
  - 'autoprefixer'
  - 'cssmin'

images:
  - 'concurrent:images'

markup:
  - 'jade:index'
  - 'newer:copy:static'
  - 'processhtml'
  - 'htmlcompressor'